### ISSUE TITLE
Summary is too long

### ISSUE THREAD

**Issue by razzeee** [flathub/com.blockstream.Green#3]
We recommend to keep summaries shorter https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines#not-too-long-1

**Comment by grubles** [comment]
Thank you for pointing this out. I'll trim down the summary.

**Comment by razzeee** [comment]
Seems like it's shorter now, but still ends with a fullstop (.) - which ideally it shouldn't :)

**Comment by grubles** [comment]
Fixed in #5
